pipeline {
  agent { docker { 
      label 'windows'
      image 'python:3.8.1' 
      } 
    }
  stages {
    stage('build') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }
    stage('test') {
      steps {
        sh 'python test_calculator.py'
      }   
    }
  }
}